spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

server.port=${PORT:8081}



spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver


spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.security.user.name=${ADMIN_USER:kunal}
spring.security.user.password=${ADMIN_PASSWORD}

logging.level.org.springframework.web=DEBUG

spring.datasource.hikari.maximum-pool-size=2
spring.datasource.hikari.minimum-idle=1
spring.datasource.hikari.idle-timeout=30000
spring.datasource.hikari.max-lifetime=1800000
spring.datasource.hikari.connection-timeout=30000

# Helps prevent connection leaks
spring.datasource.hikari.leak-detection-threshold=2000


#spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.format_sql=true
#
#server.port=${PORT:8081}
#
#
#
#spring.datasource.url=jdbc:postgresql://aws-1-ap-south-1.pooler.supabase.com:5432/postgres?prepareThreshold=0
#spring.datasource.username=postgres.zpwdhvlxdibzarahtlxf
#spring.datasource.password=KobeIsMyHomie
#spring.datasource.driver-class-name=org.postgresql.Driver
#
#
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
#
#spring.security.user.name=${ADMIN_USER:kunal}
#spring.security.user.password=password
#
#logging.level.org.springframework.web=DEBUG
#
#spring.datasource.hikari.maximum-pool-size=2
#spring.datasource.hikari.minimum-idle=1
#spring.datasource.hikari.idle-timeout=30000
#spring.datasource.hikari.max-lifetime=1800000
#spring.datasource.hikari.connection-timeout=30000
#
## Helps prevent connection leaks
#spring.datasource.hikari.leak-detection-threshold=2000
#
#app.jwt-secret-key=8894a1d2ee16a918505b8a9816962c01099365398c99f9790640baea33aff243
#app.jwt-expiration-ms=86400000
